<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DotPulsar" Version="4.2.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Comandas.Domain\Comandas.Domain.csproj" />
    <ProjectReference Include="..\Comandas.Shared\Comandas.Shared.csproj" />
	  <ProjectReference Include="..\Comandas.Data\Comandas.Data.csproj" />
  </ItemGroup>

</Project>
